[package]
name = "starship_plugin_directory"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
starship_bindings = { version = "0.1.0", path = "../protocol/bindings/rust-plugin" }
