[package]
name = "starshipd"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2021"

[dependencies]
anyhow = "1.0.71"
fp-bindgen-support = { version = "3.0.0", features = ["wasmer2_host", "async"] }
serde = { version = "1.0.164", features = ["derive"] }
wasmer = { version = "2", features = ["compiler", "cranelift", "singlepass"] }
